CREATE TABLE IF NOT EXISTS crawl_job (
    id UUID PRIMARY KEY,
    seed_url VARCHAR(2048) NOT NULL,
    root_host VARCHAR(255) NOT NULL,
    max_pages INT NOT NULL,
    max_depth INT NOT NULL,
    same_host_only BOOLEAN NOT NULL,
    respect_robots BOOLEAN NOT NULL,
    requests_per_second DOUBLE PRECISION NOT NULL,
    status VARCHAR(32) NOT NULL,
    pages_crawled INT NOT NULL DEFAULT 0,
    pages_failed INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    error_message VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS crawl_frontier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL,
    depth INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    discovered_from VARCHAR(2048),
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_frontier_job FOREIGN KEY (job_id) REFERENCES crawl_job(id) ON DELETE CASCADE,
    CONSTRAINT uq_frontier_job_url UNIQUE (job_id, canonical_url)
);

CREATE INDEX IF NOT EXISTS idx_frontier_ready
    ON crawl_frontier(job_id, status, next_attempt_at, depth, id);

CREATE TABLE IF NOT EXISTS crawled_page (
    id UUID PRIMARY KEY,
    job_id UUID NOT NULL,
    url VARCHAR(2048) NOT NULL,
    depth INT NOT NULL,
    status_code INT NOT NULL,
    content_type VARCHAR(255),
    title VARCHAR(1000),
    body_sha256 VARCHAR(64) NOT NULL,
    extracted_text CLOB,
    outbound_links INT NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_page_job FOREIGN KEY (job_id) REFERENCES crawl_job(id) ON DELETE CASCADE,
    CONSTRAINT uq_page_job_url UNIQUE (job_id, url)
);

CREATE INDEX IF NOT EXISTS idx_page_job_fetched
    ON crawled_page(job_id, fetched_at);

CREATE TABLE IF NOT EXISTS career_scan (
    job_id UUID PRIMARY KEY,
    careers_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_career_scan_job FOREIGN KEY (job_id) REFERENCES crawl_job(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS job_posting (
    id UUID PRIMARY KEY,
    scan_id UUID NOT NULL,
    page_id UUID NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    company VARCHAR(500),
    location VARCHAR(1000),
    skills CLOB,
    experience VARCHAR(1000),
    employment_type VARCHAR(500),
    description CLOB,
    extraction_method VARCHAR(32) NOT NULL,
    discovered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_posting_scan FOREIGN KEY (scan_id) REFERENCES career_scan(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_posting_page FOREIGN KEY (page_id) REFERENCES crawled_page(id) ON DELETE CASCADE,
    CONSTRAINT uq_posting_scan_url UNIQUE (scan_id, source_url)
);

CREATE INDEX IF NOT EXISTS idx_posting_scan_discovered
    ON job_posting(scan_id, discovered_at);
