CREATE TABLE IF NOT EXISTS crawl_job (
    id UUID PRIMARY KEY,
    seed_url VARCHAR(2048) NOT NULL,
    root_host VARCHAR(255) NOT NULL,
    max_pages INT NOT NULL,
    max_depth INT NOT NULL,
    same_host_only BOOLEAN NOT NULL,
    respect_robots BOOLEAN NOT NULL,
    requests_per_second DOUBLE PRECISION NOT NULL,
    status VARCHAR(32) NOT NULL,
    pages_crawled INT NOT NULL DEFAULT 0,
    pages_failed INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    error_message VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS crawl_frontier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL,
    depth INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    discovered_from VARCHAR(2048),
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_frontier_job FOREIGN KEY (job_id) REFERENCES crawl_job(id) ON DELETE CASCADE,
    CONSTRAINT uq_frontier_job_url UNIQUE (job_id, canonical_url)
);

CREATE INDEX IF NOT EXISTS idx_frontier_ready
    ON crawl_frontier(job_id, status, next_attempt_at, depth, id);

CREATE TABLE IF NOT EXISTS crawled_page (
    id UUID PRIMARY KEY,
    job_id UUID NOT NULL,
    url VARCHAR(2048) NOT NULL,
    depth INT NOT NULL,
    status_code INT NOT NULL,
    content_type VARCHAR(255),
    title VARCHAR(1000),
    body_sha256 VARCHAR(64) NOT NULL,
    extracted_text CLOB,
    outbound_links INT NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_page_job FOREIGN KEY (job_id) REFERENCES crawl_job(id) ON DELETE CASCADE,
    CONSTRAINT uq_page_job_url UNIQUE (job_id, url)
);

CREATE INDEX IF NOT EXISTS idx_page_job_fetched
    ON crawled_page(job_id, fetched_at);
